---
- name: Include install.yml file conditionally
  include_tasks: install.yml
  when: (install_varnish | bool)

- name: Include uninstall.yml file conditionally
  include_tasks: uninstall.yml
  when: not (install_varnish | bool)
