---

- name: force systemd to reread configs
  systemd:
    daemon_reload: true

- name: restart and enable varnish service
  systemd:
    name: varnish
    state: restarted
    enabled: true
    daemon_reload: true
